#####
# Ambiente 1.0
# quasar-framework-cli builds uses the default node image
######
FROM ambientum/node:6

# Repository/Image Maintainer
MAINTAINER Joao Lemgruber <jclemgruber@gmail.com>

# Install quasar-framework-cli v0.8.2
RUN npm install -g quasar-cli
