#####
# Ambiente 1.0
# Android as Base Image
######
FROM ambiente/android

# Repository/Image Maintainer
MAINTAINER Joao Lemgruber <jclemgruber@gmail.com>

WORKDIR "/var/www/app"

RUN npm i -g --unsafe-perm cordova
