#####
# Ambiente 1.0
# Nodejs as Base Image (Node Packages)
######
FROM ambiente/nodejs

# Repository/Image Maintainer
MAINTAINER Joao Lemgruber <jclemgruber@gmail.com>

WORKDIR "/var/www/app"

RUN npm i -g --unsafe-perm quasar-cli
